"""eliminacion correcta

Revision ID: ad35a2f86200
Revises: d92641791660
Create Date: 2023-09-15 16:34:59.775460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad35a2f86200'
down_revision = 'd92641791660'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('modelselection_reg_id_fkey', 'modelselection', type_='foreignkey')
    op.drop_constraint('modelselection_seg_id_fkey', 'modelselection', type_='foreignkey')
    op.create_foreign_key(None, 'modelselection', 'regressionmodel', ['reg_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'modelselection', 'segmentationmodel', ['seg_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'modelselection', type_='foreignkey')
    op.drop_constraint(None, 'modelselection', type_='foreignkey')
    op.create_foreign_key('modelselection_seg_id_fkey', 'modelselection', 'segmentationmodel', ['seg_id'], ['id'])
    op.create_foreign_key('modelselection_reg_id_fkey', 'modelselection', 'regressionmodel', ['reg_id'], ['id'])
    # ### end Alembic commands ###
