"""cascade en herencia

Revision ID: d92641791660
Revises: dc1ca4f63afd
Create Date: 2023-09-15 16:32:37.691626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd92641791660'
down_revision = 'dc1ca4f63afd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('regressionmodel_id_fkey', 'regressionmodel', type_='foreignkey')
    op.create_foreign_key(None, 'regressionmodel', 'model', ['id'], ['id'], ondelete='cascade')
    op.drop_constraint('segmentationmodel_id_fkey', 'segmentationmodel', type_='foreignkey')
    op.create_foreign_key(None, 'segmentationmodel', 'model', ['id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'segmentationmodel', type_='foreignkey')
    op.create_foreign_key('segmentationmodel_id_fkey', 'segmentationmodel', 'model', ['id'], ['id'])
    op.drop_constraint(None, 'regressionmodel', type_='foreignkey')
    op.create_foreign_key('regressionmodel_id_fkey', 'regressionmodel', 'model', ['id'], ['id'])
    # ### end Alembic commands ###
