"""correccion cascade

Revision ID: dc1ca4f63afd
Revises: 0264a2946005
Create Date: 2023-09-15 16:27:37.221341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc1ca4f63afd'
down_revision = '0264a2946005'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('modelselection_reg_id_fkey', 'modelselection', type_='foreignkey')
    op.drop_constraint('modelselection_seg_id_fkey', 'modelselection', type_='foreignkey')
    op.create_foreign_key(None, 'modelselection', 'segmentationmodel', ['seg_id'], ['id'])
    op.create_foreign_key(None, 'modelselection', 'regressionmodel', ['reg_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'modelselection', type_='foreignkey')
    op.drop_constraint(None, 'modelselection', type_='foreignkey')
    op.create_foreign_key('modelselection_seg_id_fkey', 'modelselection', 'segmentationmodel', ['seg_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('modelselection_reg_id_fkey', 'modelselection', 'regressionmodel', ['reg_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
