"""Mejora relacciones

Revision ID: f9342dd338df
Revises: d5dcfa15191a
Create Date: 2023-09-01 02:42:42.700824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9342dd338df'
down_revision = 'd5dcfa15191a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modelselection', sa.Column('reg_id', sa.Integer(), nullable=False))
    op.add_column('modelselection', sa.Column('seg_id', sa.Integer(), nullable=False))
    op.drop_constraint('modelselection_reg_model_fkey', 'modelselection', type_='foreignkey')
    op.drop_constraint('modelselection_seg_model_fkey', 'modelselection', type_='foreignkey')
    op.create_foreign_key(None, 'modelselection', 'regressionmodel', ['reg_id'], ['id'])
    op.create_foreign_key(None, 'modelselection', 'segmentationmodel', ['seg_id'], ['id'])
    op.drop_column('modelselection', 'seg_model')
    op.drop_column('modelselection', 'reg_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modelselection', sa.Column('reg_model', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('modelselection', sa.Column('seg_model', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'modelselection', type_='foreignkey')
    op.drop_constraint(None, 'modelselection', type_='foreignkey')
    op.create_foreign_key('modelselection_seg_model_fkey', 'modelselection', 'segmentationmodel', ['seg_model'], ['id'])
    op.create_foreign_key('modelselection_reg_model_fkey', 'modelselection', 'regressionmodel', ['reg_model'], ['id'])
    op.drop_column('modelselection', 'seg_id')
    op.drop_column('modelselection', 'reg_id')
    # ### end Alembic commands ###
