"""Fecha y archivo de creacion

Revision ID: ff90c8aaa00a
Revises: 3d2b7c34107d
Create Date: 2023-08-29 17:50:38.565681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff90c8aaa00a'
down_revision = '3d2b7c34107d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
